inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4

Style/CollectionMethods:
  PreferredMethods:
    find: detect
    reduce: inject
    collect: map
    find_all: select

Bundler/OrderedGems:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/BlockDelimiters:
  EnforcedStyle: line_count_based

Layout/DotPosition:
  EnforcedStyle: leading

Metrics/BlockLength:
  Enabled: false
